apiVersion: v1
kind: ConfigMap
metadata:
  name: ruleta-almuerzos-config
  namespace: ruleta-almuerzos
  labels:
    app: ruleta-almuerzos
data:
  # Configuraciones de la aplicaci√≥n
  APP_NAME: "Ruleta de Almuerzos"
  APP_VERSION: "1.0.0"
  ENVIRONMENT: "production"
